<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Playground.JobFinder-98de26b4-1c95-4f0d-a39a-b1c2fdc6e90d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Playground.JobFinder.Client\Playground.JobFinder.Client.csproj" />
    <PackageReference Include="AutoMapper" Version="16.0.0-beta-1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.11" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Job\Pages\" />
    <Folder Include="Models\Responses\" />
    <Folder Include="Models\Requests\" />
    <Folder Include="Middlewares\" />
    <Folder Include="Supports\Repositories\" />
    <Folder Include="wwwroot\assets\" />
  </ItemGroup>

</Project>
