services:
  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Microservices/Product/Product.API/Dockerfile

  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: Microservices/Cart/Cart.API/Dockerfile

  cartdb:
    image: mcr.microsoft.com/mssql/server:2017-latest 
  
  productdb:
    image: postgres

  pgdbadmin:
    image: dpage/pgadmin4
   
  eventstore:
    image: eventstore/eventstore:21.6.0-buster-slim
    
  rabbitmq:
    image: rabbitmq:3-management
   
# <------------------- BEGIN | Apache solutions ----------------->
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
  
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - "9092:9092"
# <---------------- END | Apache solutions ----------------->


# <----------------- START | File/Object Storage ---------------------->
  minio:
    image: minio/minio:latest
    

# <------------------ END | File/Object Storage ----------------------->


# <------------------ START | Vector Database ------------------------->
# pg-vector db 
  pg_vector:
    image: pgvector/pgvector:pg16

# milvus 
  milvus-etcd:
    image: quay.io/coreos/etcd:v3.5.25
  milvus-standalone:
    image: milvusdb/milvus:v2.6.7
# <------------------ END | Vector Database --------------------------->

  # emailnotification.api:
  #   image: ${DOCKER_REGISTRY-}emailnotification
  #   build:
  #     context: .
  #     dockerfile: EmailNotification.API/Dockerfile

  # emailnotificationdb:
  #   image: mcr.microsoft.com/mssql/server:2017-latest 
  
  # timerjob:
  #   image: ${DOCKER_REGISTRY-}timerjob
  #   build:
  #     context: .
  #     dockerfile: EmailNotification.CronJobWorker/Dockerfile


volumes:
  postgres_data:
  pgadmin_data:
  