

services:

  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_HTTP_PORTS=8080
#      - ASPNETCORE_URLS=http://*:8003
      - "DatabaseSettings__ConnectionString=Server=productdb;Port=5432;Database=ProductDb;User Id=admin;Password=admin1234;"  
    depends_on:
      - productdb
    ports:
      - "8007:8080"
  cart.api:
    container_name: cart.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings__DatabaseConnectionString=Server=cartdb;Database=CartDb;User Id=sa;Password=1qaz2wsx;TrustServerCertificate=True;"
#      - ASPNETCORE_URLS=http://*:8003
      - "GrpcSettings__ProductUrl=http://product.api:8080"
    depends_on:
      - cartdb
    ports:
      - "8008:8080"
  cartdb:
    container_name: cartdb
    environment:
      SA_PASSWORD: "1qaz2wsx"
      ACCEPT_EULA: "Y"
    restart: always
    ports: 
      - "1733:1733"

  productdb:
    container_name: productdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=ProductDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgdbadmin:
    container_name: pgdbadmin
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@eCommerce.net
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5051:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
  
  eventstore:
    container_name: eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=ALL
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
   
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbit-mq
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RBBITMQ_DEFAULT_PASS: guest
  # <---------------- BEGIN | Apache solutions ----------------->

  zookeeper:
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # <---------------- END | Apache solutions ------------------->
  

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
   
        

  # emailnotification.api:
  #   container_name: emailnotification.api
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - "ConnectionStrings__DatabaseConnectionString=Server=emailnotificationdb;Database=UserDb;User Id=sa;Password=1qaz2wsx;TrustServerCertificate=True"
  #   depends_on:
  #     - emailnotificationdb
  #   ports:
  #     - "8003:8080"
      
  # emailnotificationdb:
  #   container_name: emailnotificationdb
  #   environment:
  #     SA_PASSWORD: "1qaz2wsx"
  #     ACCEPT_EULA: "Y"
  #   restart: always
  #   ports: 
  #     - "1533:1533"
  # timerjob:
  #   container_name: timerjob
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - "ServiceUrls__EmailNotification=http://emailnotification.api:8080"
  #   ports:
  #     - "8002:8080"
  #   depends_on:
  #     - emailnotification.api


  
    
  