services:
  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Microservices/Product/Product.API/Dockerfile

  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: Microservices/Cart/Cart.API/Dockerfile

  cartdb:
    image: mcr.microsoft.com/mssql/server:2017-latest 
  
  productdb:
    image: postgres

  pgdbadmin:
    image: dpage/pgadmin4

  # emailnotification.api:
  #   image: ${DOCKER_REGISTRY-}emailnotification
  #   build:
  #     context: .
  #     dockerfile: EmailNotification.API/Dockerfile

  # emailnotificationdb:
  #   image: mcr.microsoft.com/mssql/server:2017-latest 
  
  # timerjob:
  #   image: ${DOCKER_REGISTRY-}timerjob
  #   build:
  #     context: .
  #     dockerfile: EmailNotification.CronJobWorker/Dockerfile


volumes:
  postgres_data:
  pgadmin_data:
  