<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="OrderContext\Behaviours\" />
    <Folder Include="OrderContext\Enumerations\" />
    <Folder Include="OrderContext\Repositories\" />
    <Folder Include="Extensions\" />
  </ItemGroup>

</Project>
