<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="MaterializedView\" />
    <Folder Include="Extensions\" />
    <Folder Include="BehaviourExtensions\" />
    <Folder Include="Support\" />
    <Folder Include="Replacement\" />
  </ItemGroup>

</Project>
