<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Domain\" />
    <Folder Include="Kafka\Core\InventoryDomain\" />
    <Folder Include="Kafka\Core\OrderDomain\Events\" />
    <Folder Include="Kafka\Core\SharedKernel\" />
    <Folder Include="Kafka\Core\UserDomain\Events\" />
    <Folder Include="Kafka\Core\UserDomain\Enumerations\" />
    <Folder Include="Kafka\Interfaces\" />
    <Folder Include="Kafka\Configurations\" />
    <Folder Include="Kafka\Mappers\" />
    <Folder Include="Kafka\Models\Notification\" />
    <Folder Include="Kafka\Models\Order\" />
    <Folder Include="Kafka\Notification\" />
    <Folder Include="Kafka\RelationalDb\Data\" />
    <Folder Include="Kafka\Services\Consumers\" />
    <Folder Include="MCP\Resources\" />
    <Folder Include="MCP\Prompts\" />
    <Folder Include="MCP\Tools\" />
    <Folder Include="MinimalApiEndpoints\" />
    <Folder Include="HealthCheck\" />
    <Folder Include="SemanticKernel\Connectors\" />
    <Folder Include="SemanticKernel\Services\" />
    <Folder Include="SemanticKernel\Storage\Minio\" />
    <Folder Include="SemanticKernel\Storage\Blob\" />
    <Folder Include="SemanticKernel\Storage\S3\" />
    <Folder Include="SemanticKernel\Storage\SqlLite\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="A2A" Version="0.3.3-preview" />
    <PackageReference Include="AutoMapper" Version="15.1.0" />
    <PackageReference Include="Confluent.Kafka" Version="2.12.0" />
    <PackageReference Include="MassTransit" Version="8.5.5" />
    <PackageReference Include="MassTransit.Abstractions" Version="8.5.5" />
    <PackageReference Include="MassTransit.Extensions.DependencyInjection" Version="7.3.1" />
    <PackageReference Include="MassTransit.MongoDb" Version="8.5.5" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0-rc.2.25502.107" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.67.1" />
    <PackageReference Include="ModelContextProtocol" Version="0.4.0-preview.3" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="0.4.0-preview.3" />
    <PackageReference Include="ModelContextProtocol.Core" Version="0.4.0-preview.3" />
  </ItemGroup>

</Project>
